const fs = require('fs');
const path = require('path');
const pool = require('../config/db');

const quoteIdentifier = (identifier) => `\`${String(identifier).replace(/`/g, '``')}\``;

const quoteValue = (value) => {
  if (value === null || value === undefined) return 'NULL';
  if (Buffer.isBuffer(value)) return `X'${value.toString('hex')}'`;
  if (value instanceof Date) return `'${value.toISOString().slice(0, 19).replace('T', ' ')}'`;
  if (typeof value === 'number' && Number.isFinite(value)) return String(value);
  if (typeof value === 'bigint') return String(value);
  if (typeof value === 'boolean') return value ? '1' : '0';

  const text = String(value)
    .replace(/\\/g, '\\\\')
    .replace(/\0/g, '\\0')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\u001a/g, '\\Z')
    .replace(/'/g, "''");
  return `'${text}'`;
};

const getCreateStatement = async (connection, tableName) => {
  const [rows] = await connection.query(`SHOW CREATE TABLE ${quoteIdentifier(tableName)}`);
  const createStatement = rows[0] && Object.values(rows[0])[1];
  if (!createStatement) throw new Error(`Unable to read schema for table ${tableName}.`);
  return String(createStatement).replace(/;\s*$/, '');
};

const buildTableDump = async (connection, tableName) => {
  const createStatement = await getCreateStatement(connection, tableName);
  const [rows] = await connection.query(`SELECT * FROM ${quoteIdentifier(tableName)}`);
  const lines = [`DROP TABLE IF EXISTS ${quoteIdentifier(tableName)};`, `${createStatement};`];

  if (rows.length) {
    const columns = Object.keys(rows[0]);
    const columnList = columns.map(quoteIdentifier).join(', ');
    const values = rows.map((row) => `(${columns.map((column) => quoteValue(row[column])).join(', ')})`);
    lines.push(`INSERT INTO ${quoteIdentifier(tableName)} (${columnList}) VALUES\n${values.join(',\n')};`);
  }

  return lines.join('\n');
};

const pruneExpiredBackups = async (backupDirectory, retentionDays, currentBackupPath) => {
  if (!Number.isInteger(retentionDays) || retentionDays < 7 || retentionDays > 90) return 0;
  const cutoff = Date.now() - retentionDays * 24 * 60 * 60 * 1000;
  const entries = await fs.promises.readdir(backupDirectory, { withFileTypes: true });
  let removed = 0;

  for (const entry of entries) {
    if (!entry.isFile() || !/^ipes-.+\.sql$/i.test(entry.name)) continue;
    const filePath = path.join(backupDirectory, entry.name);
    if (path.resolve(filePath) === path.resolve(currentBackupPath)) continue;
    const stats = await fs.promises.stat(filePath);
    if (stats.mtimeMs < cutoff) {
      await fs.promises.unlink(filePath);
      removed += 1;
    }
  }

  return removed;
};

const createDatabaseBackup = async () => {
  const backupDirectory = path.join(__dirname, '..', 'backups');
  await fs.promises.mkdir(backupDirectory, { recursive: true });

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const fileName = `ipes-${timestamp}.sql`;
  const filePath = path.join(backupDirectory, fileName);
  const connection = await pool.getConnection();

  try {
    const [tableRows] = await connection.query(`
      SELECT TABLE_NAME
      FROM information_schema.TABLES
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_TYPE = 'BASE TABLE'
      ORDER BY TABLE_NAME ASC
    `);

    const dumpParts = [
      '-- IPES database backup generated by the Node.js backup service',
      `-- Generated at ${new Date().toISOString()}`,
      'SET FOREIGN_KEY_CHECKS = 0;',
      'SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";',
      '',
    ];

    for (const row of tableRows) {
      dumpParts.push(`-- Table: ${row.TABLE_NAME}`);
      dumpParts.push(await buildTableDump(connection, row.TABLE_NAME));
      dumpParts.push('');
    }

    dumpParts.push('SET FOREIGN_KEY_CHECKS = 1;', '');
    await fs.promises.writeFile(filePath, dumpParts.join('\n'), 'utf8');

    const stat = await fs.promises.stat(filePath);
    const backupTime = new Date().toISOString();
    await pool.query(
      `INSERT INTO system_settings (setting_key, setting_value)
       VALUES ('last_backup', ?)
       ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value), updated_at = CURRENT_TIMESTAMP`,
      [backupTime]
    );
    let removedExpiredBackups = 0;
    try {
      const [[retentionRow]] = await pool.query("SELECT setting_value FROM system_settings WHERE setting_key = 'backup_retention_days' LIMIT 1");
      const retentionDays = Number.parseInt(retentionRow?.setting_value, 10) || 7;
      removedExpiredBackups = await pruneExpiredBackups(backupDirectory, retentionDays, filePath);
    } catch (error) {
      console.warn('Backup retention cleanup failed:', error?.message || error);
    }

    return {
      success: true,
      filePath,
      fileName,
      sizeBytes: stat.size,
      createdAt: backupTime,
      removedExpiredBackups,
      message: 'Database backup created successfully.',
    };
  } finally {
    connection.release();
  }
};

module.exports = {
  createDatabaseBackup,
};
