ALTER TABLE audit_logs
  ADD COLUMN IF NOT EXISTS actor_user_id INT UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS actor_email VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS actor_role VARCHAR(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS category VARCHAR(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS target_details TEXT,
  ADD COLUMN IF NOT EXISTS route_path VARCHAR(512) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS http_method VARCHAR(12) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS status_code SMALLINT UNSIGNED DEFAULT NULL;